COLUMNS = ['Año',
'Mes',
# 'Total de empleo formal en el sector privado (miles de trabajadores',
# 'Venta de autoservicios (Var. % nominal)',
# 'Venta de equipamiento del hogar (Var. % nominal)',
# 'Venta de ferretería y otros (Var. % nominal)',
# 'Venta de librerías (Var. % nominal)',
# 'Venta de tiendas por departamento (Var. % nominal)',
# 'Venta de productos farmaceúticos (Var. % nominal)',
# 'Empleo formal privado (var%) ',
# 'Salario promedio real del sector formal privado (Var.% anual)',
# 'Masa salarial real del sector formal privado (Var.% anual)',
# 'Masa salarial nominal del sector formal privado (millones de s/)',
# 'Masa salarial nominal del sector formal privado (Var.% anual)',
# 'Masa salarial real del sector formal privado (millones de s/)',
# 'Índice de confianza del consumidor (puntos)',
# 'Consumo - Morosidad (%)',
# 'Monto de transacciones con tarjetas de débito (Var. % anual nominal)',
# 'Monto de transacciones con tarjetas de crédito (Var. % anual nominal)',
# 'Cantidad de transacciones con tarjetas de débito (Var. % anual)',
# 'Cantidad de transacciones con tarjetas de crédito (Var. % anual)',
# 'Venta de autoservicios (S/ miles)',
# 'Venta de equipamiento del hogar (S/ miles)',
# 'Venta de ferretería y otros (S/ miles)',
# 'Venta de librerías (S/ miles)',
# 'Venta de productos farmaceúticos (S/ miles)',
# 'Venta de tiendas por departamento (S/ miles)',
# 'Venta de retail moderno (S/ miles)',
# 'Venta de retail moderno (Var. % nominal)',
# 'Venta (inmatriculación) de vehículos livianos (un.)',
# 'Venta (inmatriculación) de vehículos pesados (un.)',
# 'Venta de vehículos usados livianos (unidades)',
# 'Venta de vehículos usados menores, ligeros y pesados - Total (un.)',
# 'Tasa de referencia FED (%)',
# 'Gasto público en construcción total (Var. % real)',
# 'Gasto público en construcción Zona Norte (Var. % real)',
# 'Gasto público en construcción Zona Sur (Var. % real)',
# 'Gasto público en construcción Zona Oriente (Var. % real)',
# 'Gasto público en construcción Zona Centro (Var. % real)',
# 'Gasto público en construcción - Amazonas (var. % real anual)',
# 'Gasto público en construcción - Ancash (var. % real anual)',
# 'Gasto público en construcción - Apurimac (var. % real anual)',
# 'Gasto público en construcción - Arequipa (var. % real anual)',
# 'Gasto público en construcción - Ayacucho (var. % real anual)',
# 'Gasto público en construcción - Cajamarca (var. % real anual)',
# 'Gasto público en construcción - Callao (var. % real anual)',
# 'Gasto público en construcción - Cusco (var. % real anual)',
# 'Gasto público en construcción - Huancavelica (var. % real anual)',
# 'Gasto público en construcción - Huanuco (var. % real anual)',
# 'Gasto público en construcción - Ica (var. % real anual)',
# 'Gasto público en construcción - Junin (var. % real anual)',
# 'Gasto público en construcción - La libertad (var. % real anual)',
# 'Gasto público en construcción - Lambayeque (var. % real anual)',
# 'Gasto público en construcción - Lima (var. % real anual)',
# 'Gasto público en construcción - Loreto (var. % real anual)',
# 'Gasto público en construcción - Madre de Dios (var. % real anual)',
# 'Gasto público en construcción - Moquegua (var. % real anual)',
# 'Gasto público en construcción - Pasco (var. % real anual)',
# 'Gasto público en construcción - Piura (var. % real anual)',
# 'Gasto público en construcción - Puno (var. % real anual)',
# 'Gasto público en construcción - San Martín (var. % real anual)',
# 'Gasto público en construcción - Tacna (var. % real anual)',
# 'Gasto público en construcción - Tumbes (var. % real anual)',
# 'Gasto público en construcción - Ucayali (var. % real anual)',
# 'Confianza del consumidor - Componente: Precio Presente',
# 'Confianza del consumidor - Componente: Familia Presente',
# 'Confianza del consumidor - Componente: Familia Futuro',
# 'Confianza del consumidor - Componente: Trabajo Presente',
# 'Confianza del consumidor -  Puntos NSE A',
# 'Confianza del consumidor - Puntos NSE B',
# 'Confianza del consumidor - Puntos NSE C',
# 'Confianza del consumidor - Puntos NSE D',
# 'Confianza del consumidor - Puntos NSE E',
# 'Índice de confianza para contratar: Incorporar (%)',
# 'Confianza para contratar: Mantener (%)',
# 'Confianza para contratar: Reducir (%)',
# 'Confianza para contratar (puntos)',
# 'Confianza para invertir: Acelerar (%)',
# 'Confianza para invertir: Mantener (%)',
# 'Confianza para invertir: Reducir (%)',
# 'Confianza para invertir (puntos)',
'Créditos otorgados para venta de vivienda: Banca Múltiple (número)',
'Créditos otorgados para venta de vivienda: Financieras (número)',
'Créditos otorgados para venta de vivienda: Cajas Municipales (número)',
'Créditos otorgados para venta de vivienda: Cajas Rurales (número)',
'Créditos otorgados para venta de vivienda: Edpymes (número)',
'Total créditos hipotecarios (número) ',
'Total créditos hipotecarios (Var.% anual)',
'Inflación de Argentina - fdp (%)',
'Inflación de Bolivia - fdp (%)',
'Inflación de Brasil - fdp (%)',
'Inflación de Chile - fdp (%)',
'Inflación de Colombia - fdp (%)',
'Inflación de Ecuador - fdp (%)',
'Inflación de México - fdp (%)',
'Inflación mundial - fdp (%)',
'Inversión Minera - (millones de soles de diciembre de 2021)',
'Inversión Minera (var % real)',
'Exportaciones mineras (US$ millones)',
'Exportaciones mineras (Var.% nominal)',
'Costo global de contenedores (US$ por cont. de 40 pies)',
'Confiabilidad de tiempos de entrega (% de naves que llegó a tiempo a su destino)',
'Retraso promedio de llegadas tardías (Días de retraso)',
'Costo global de es por ruta - Asia Oriental a la Costa Oeste de América del Norte (US$ por cont. de 40 pies)',
'Costo global de es por ruta - Asia Oriental a la Costa Este de América del Norte (US$ por cont. de 40 pies)',
'Índice Big Data de Consumo BBVA (Var % anual real)',
'Demanda eléctrica total (Var.%)',
'Avance físico de obras públicas (Var.% anual)',
'Consumo interno de cemento (Var.%)',
#'IR de 5ta categoría  (Var. % anual real, promedio móvil 3 meses) ',
#'Aportaciones a ESSALUD    (Var. % anual real, promedio móvil 3 meses) ',
'IGV Interno (Var. % real)',
'Nivel de demanda con respecto a lo esperado (Puntos)',
'Nivel de demanda con respecto a lo esperado (Diferencia)',
'Gasohol regular (Soles por galón)',
'Gasohol premium (Soles por galón)',
'Ventas de empresas de manufactura de alimentos y bebidas (var. % nominal)',
'PBI restaurantes (Var.% real) - Nacional',
'Tasa de interés hasta 360 días - corporativo (%)',
'Tasa de interés hasta 360 días - gran empresa (%)',
'Tasa de interés hasta 360 días - mediana empresa (%)',
'Tasa de interés hasta 360 días - pequeña empresa (%)',
'Tasa de interés hasta 360 días - micro empresa (%)',
# 'Empleo formal - agropecuario y pesca (miles de trabajadores) ', 
# 'Empleo formal - minería e hidrocarburos (miles de trabajadores) ', 
#  'Empleo formal - industria (miles de trabajadores)', 
# 'Empleo formal - construcción (miles de trabajadores)', 
# 'Empleo formal - comercio (miles de trabajadores)', 
# 'Empleo formal - servicios (miles de trabajadores)', 
# 'Empleo formal - agropecuario y pesca (Var.%) ', 
# 'Empleo formal - mineria e hidrocarburos (Var.%)', 
# 'Empleo formal - industria (Var.%)', 
# 'Empleo formal - construcción (Var.%)', 
# 'Empleo formal - comercio (Var.%)', 
# 'Empleo formal - servicios (Var.%)', 
'Tipo de cambio de Argentina (peso argentino por US$, pdp) ', 
'Tipo de cambio de Bolivia (boliviano por US$, pdp)', 
'Tipo de cambio de Brasil (real brasileño por US$, pdp)', 
'Tipo de cambio de Chile (peso chileno por US$, pdp)', 
'Tipo de cambio de Colombia (peso colombiano por US$, pdp)', 
'Tipo de cambio de México (peso mexicano por US$, pdp)', 
'Tipo de cambio de Corea del Sur (won coreano por US$, fdp)', 
'Tipo de cambio de Eurozona (Euro por US$, fdp)', 
'Tipo de cambio de Tailandia (baht tailandés por US$, fdp)', 
'Tipo de cambio de Indonesia (rupia indonesia por US$, fdp)', 
'Tipo de cambio IDR (Rupia indonesia por US$)', 
'Tipo de cambio THB (Baht tailandés por US$)',
'Tipo de cambio de Japon (yen por US$, pdp)'
]


TABLE_NAMES_PER_COLUMN = {'PBI (Var.% real)': 'pbi_mes',
# 'Tipo de cambio, promedio de periodo (S/US$)': 'financiero_mes',
# 'Inflación anual Lima Metropolitana (%)': 'inflacion_mes',
# 'Crédito de consumo (Var.% nominal anual)': 'financiero_mes',
# 'Consumo - Morosidad (%)': 'financiero_mes',
# 'Monto de transacciones con tarjetas de débito (Var. % anual nominal)': 'financiero_mes',
# 'Monto de transacciones con tarjetas de crédito (Var. % anual nominal)': 'financiero_mes',
# 'Cantidad de transacciones con tarjetas de débito (Var. % anual)': 'financiero_mes',
# 'Cantidad de transacciones con tarjetas de crédito (Var. % anual)': 'financiero_mes',

# 'Tipo de cambio libra esterlina por US$  (pdp)': 'financiero_mes',
# 'Tasa de interés hasta 360 días - corporativo (%)': 'financiero_mes',
# 'Tasa de interés hasta 360 días - gran empresa (%)': 'financiero_mes',
# 'Tasa de interés hasta 360 días - mediana empresa (%)': 'financiero_mes',
# 'Tasa de interés hasta 360 días - pequeña empresa (%)': 'financiero_mes',
# 'Tasa de interés hasta 360 días - micro empresa (%)': 'financiero_mes',
# 'Empleo formal - agropecuario y pesca (miles de trabajadores) ': 'financiero_mes',
# 'Empleo formal - minería e hidrocarburos (miles de trabajadores) ': 'financiero_mes',
# 'Empleo formal - industria (miles de trabajadores)': 'financiero_mes',
# 'Empleo formal - construcción (miles de trabajadores)': 'financiero_mes',
# 'Empleo formal - comercio (miles de trabajadores)': 'financiero_mes',
# 'Empleo formal - servicios (miles de trabajadores)': 'financiero_mes',
# 'Empleo formal - agropecuario y pesca (Var.%) ': 'financiero_mes',
# 'Empleo formal - mineria e hidrocarburos (Var.%)': 'financiero_mes',
# 'Empleo formal - industria (Var.%)': 'financiero_mes',
# 'Empleo formal - construcción (Var.%)': 'financiero_mes',
# 'Empleo formal - comercio (Var.%)': 'financiero_mes',
# 'Empleo formal - servicios (Var.%)': 'financiero_mes',
# 'Tipo de cambio de Argentina (peso argentino por US$, pdp) ': 'financiero_mes',
# 'Tipo de cambio de Bolivia (boliviano por US$, pdp)': 'financiero_mes',
# 'Tipo de cambio de Brasil (real brasileño por US$, pdp)': 'financiero_mes',
# 'Tipo de cambio de Chile (peso chileno por US$, pdp)': 'financiero_mes',
# 'Tipo de cambio de Colombia (peso colombiano por US$, pdp)': 'financiero_mes',
# 'Tipo de cambio de México (peso mexicano por US$, pdp)': 'financiero_mes',
# 'Tipo de cambio de Corea del Sur (won coreano por US$, fdp)': 'financiero_mes',
# 'Tipo de cambio de Eurozona (Euro por US$, fdp)': 'financiero_mes',
# 'Tipo de cambio de Tailandia (baht tailandés por US$, fdp)': 'financiero_mes',
# 'Tipo de cambio de Indonesia (rupia indonesia por US$, fdp)': 'financiero_mes',
# 'Tipo de cambio IDR (Rupia indonesia por US$)': 'financiero_mes',
# 'Tipo de cambio THB (Baht tailandés por US$)': 'financiero_mes',
'Tipo de cambio de Japon (yen por US$, pdp)': 'financiero_mes',
# 'Total de empleo formal en el sector privado (miles de trabajadores': 'empleo_ingresos_mes',
# 'Empleo formal privado (var%) ': 'empleo_ingresos_mes',
# 'Salario promedio real del sector formal privado (Var.% anual)': 'empleo_ingresos_mes',
# 'Masa salarial real del sector formal privado (Var.% anual)': 'empleo_ingresos_mes',
# 'Masa salarial nominal del sector formal privado (millones de s/)': 'empleo_ingresos_mes',
# 'Masa salarial nominal del sector formal privado (Var.% anual)': 'empleo_ingresos_mes',
# 'Masa salarial real del sector formal privado (millones de s/)': 'empleo_ingresos_mes',
# 'Índice de confianza del consumidor (puntos)': 'confianza_mes',
# 'Venta de autoservicios (S/ miles)': 'retail_mes',
# 'Venta de tiendas por departamento (S/ miles)': 'retail_mes',
# 'Venta de ferretería y otros (S/ miles)': 'retail_mes',
# 'Venta de equipamiento del hogar (S/ miles)': 'retail_mes',
# 'Venta de librerías (S/ miles)': 'retail_mes',
# 'Venta de productos farmaceúticos (S/ miles)': 'retail_mes',
# 'Venta de autoservicios (Var. % nominal)': 'retail_mes',
# 'Venta de tiendas por departamento (Var. % nominal)': 'retail_mes',
# 'Venta de ferretería y otros (Var. % nominal)': 'retail_mes',
# 'Venta de equipamiento del hogar (Var. % nominal)': 'retail_mes',
# 'Venta de librerías (Var. % nominal)': 'retail_mes',
# 'Venta de productos farmaceúticos (Var. % nominal)': 'retail_mes',
# 'Venta de retail moderno (S/ miles)': 'retail_mes',
# 'Venta de retail moderno (Var. % nominal)': 'retail_mes',
# 'Gasto público en construcción total (Var. % real)': 'construccion_regional_mes',
# 'Gasto público en construcción Zona Norte (Var. % real)': 'construccion_regional_mes',
# 'Gasto público en construcción Zona Sur (Var. % real)': 'construccion_regional_mes',
# 'Gasto público en construcción Zona Oriente (Var. % real)': 'construccion_regional_mes',
# 'Gasto público en construcción Zona Centro (Var. % real)': 'construccion_regional_mes',
# 'Gasto público en construcción - Amazonas (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Ancash (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Apurimac (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Arequipa (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Ayacucho (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Cajamarca (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Callao (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Cusco (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Huancavelica (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Huanuco (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Ica (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Junin (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - La libertad (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Lambayeque (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Lima (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Loreto (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Madre de Dios (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Moquegua (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Pasco (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Piura (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Puno (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - San Martín (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Tacna (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Tumbes (var. % real anual)': 'construccion_regional_mes',
# 'Gasto público en construcción - Ucayali (var. % real anual)': 'construccion_regional_mes',
# 'Venta (inmatriculación) de vehículos livianos (un.)': 'automotor_mes',
# 'Venta (inmatriculación) de vehículos pesados (un.)': 'automotor_mes',
# 'Venta de vehículos usados livianos (unidades)': 'automotor_mes',
# 'Venta de vehículos usados menores, ligeros y pesados - Total (un.)': 'automotor_mes',
# 'Tasa de referencia FED (%)': 'financiero_mes',
# 'Confianza del consumidor - Componente: Precio Presente': 'confianza_mes',
# 'Confianza del consumidor - Componente: Familia Presente': 'confianza_mes',
# 'Confianza del consumidor - Componente: Familia Futuro': 'confianza_mes',
# 'Confianza del consumidor - Componente: Trabajo Presente': 'confianza_mes',
# 'Confianza del consumidor -  Puntos NSE A': 'confianza_mes',
# 'Confianza del consumidor - Puntos NSE B': 'confianza_mes',
# 'Confianza del consumidor - Puntos NSE C': 'confianza_mes',
# 'Confianza del consumidor - Puntos NSE D': 'confianza_mes',
# 'Confianza del consumidor - Puntos NSE E': 'confianza_mes',
# 'Índice de confianza para contratar: Incorporar (%)': 'confianza_mes',
# 'Confianza para contratar: Mantener (%)': 'confianza_mes',
# 'Confianza para contratar: Reducir (%)': 'confianza_mes',
# 'Confianza para contratar (puntos)': 'confianza_mes',
# 'Confianza para invertir: Acelerar (%)': 'confianza_mes',
# 'Confianza para invertir: Mantener (%)': 'confianza_mes',
# 'Confianza para invertir: Reducir (%)': 'confianza_mes',
# 'Confianza para invertir (puntos)': 'confianza_mes',
'Créditos otorgados para venta de vivienda: Banca Múltiple (número)': 'vivienda_mes',
'Créditos otorgados para venta de vivienda: Financieras (número)': 'vivienda_mes',
'Créditos otorgados para venta de vivienda: Cajas Municipales (número)': 'vivienda_mes',
'Créditos otorgados para venta de vivienda: Cajas Rurales (número)': 'vivienda_mes',
'Créditos otorgados para venta de vivienda: Edpymes (número)': 'vivienda_mes',
'Total créditos hipotecarios (número) ': 'vivienda_mes',
'Total créditos hipotecarios (Var.% anual)': 'vivienda_mes',
'Inflación de Argentina - fdp (%)': 'inflacion_internacional_mes',
'Inflación de Bolivia - fdp (%)': 'inflacion_internacional_mes',
'Inflación de Brasil - fdp (%)': 'inflacion_internacional_mes',
'Inflación de Chile - fdp (%)': 'inflacion_internacional_mes',
'Inflación de Colombia - fdp (%)': 'inflacion_internacional_mes',
'Inflación de Ecuador - fdp (%)': 'inflacion_internacional_mes',
'Inflación de México - fdp (%)': 'inflacion_internacional_mes',
'Inflación mundial - fdp (%)': 'inflacion_internacional_mes',
'Inversión Minera - (millones de soles de diciembre de 2021)': 'mineria_mes',
'Inversión Minera (var % real)': 'mineria_mes',
'Exportaciones mineras (US$ millones)': 'mineria_mes',
'Exportaciones mineras (Var.% nominal)': 'mineria_mes',
'Costo global de contenedores (US$ por cont. de 40 pies)': 'logistica_mes',
'Confiabilidad de tiempos de entrega (% de naves que llegó a tiempo a su destino)': 'logistica_mes',
'Retraso promedio de llegadas tardías (Días de retraso)': 'logistica_mes',
'Costo global de es por ruta - Asia Oriental a la Costa Oeste de América del Norte (US$ por cont. de 40 pies)': 'logistica_mes',
'Costo global de es por ruta - Asia Oriental a la Costa Este de América del Norte (US$ por cont. de 40 pies)': 'logistica_mes',
'Índice Big Data de Consumo BBVA (Var % anual real)': 'consumo_mes',
'Demanda eléctrica total (Var.%)': 'electricidad_mes',
'Avance físico de obras públicas (Var.% anual)': 'construccion_mes',
'Consumo interno de cemento (Var.%)': 'construccion_mes',
#'IR de 5ta categoría  (Var. % anual real, promedio móvil 3 meses) ': 'empleo_ingresos_mes',
#'Aportaciones a ESSALUD    (Var. % anual real, promedio móvil 3 meses) ': 'empleo_ingresos_mes',
'IGV Interno (Var. % real)': 'pbi_mes',
'Nivel de demanda con respecto a lo esperado (Puntos)': 'pbi_mes',
'Nivel de demanda con respecto a lo esperado (Diferencia)': 'pbi_mes',
'Gasohol regular (Soles por galón)': 'hidrocarburos_mes',
'Gasohol premium (Soles por galón)': 'hidrocarburos_mes',
'Ventas de empresas de manufactura de alimentos y bebidas (var. % nominal)': 'ventas_nacionaleS_mes',
'PBI restaurantes (Var.% real) - Nacional': 'pbi_mes',
'Impuesto a la renta de tercera categoría - Sector agrícola (M': 'pbi_mes',
'Impuesto a la renta de tercera categoría - Sector agrícola (V': 'pbi_mes'
}

MONTHS = ['Enero', 
'Febrero', 'Marzo', 'Abril',
'Mayo',
'Junio',
'Julio',
'Agosto',
'Setiembre',
'Octubre',
'Noviembre',
'Diciembre']